name: Update Google Scholar Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Google Scholar metrics
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: |
          python <<EOF
          import requests
          import json
          from datetime import date

          url = "https://serpapi.com/search"

          params = {
              "engine": "google_scholar_author",
              "author_id": "xO32H0oAAAAJ",
              "api_key": "${SERPAPI_KEY}"
          }

          r = requests.get(url, params=params)
          data = r.json()

          author = data["author"]

          citations = author["cited_by"]["table"][0]["citations"]
          hindex = author["cited_by"]["table"][2]["citations"]
          i10 = author["cited_by"]["table"][3]["citations"]

          file = "data/metrics.json"

          with open(file) as f:
              metrics = json.load(f)

          metrics["asOf"] = str(date.today())
          metrics["scholar"]["citations"] = citations
          metrics["scholar"]["hIndex"] = hindex
          metrics["scholar"]["i10Index"] = i10

          with open(file,"w") as f:
              json.dump(metrics,f,indent=2)

          EOF


      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add data/metrics.json
          git commit -m "Automatic Google Scholar update" || exit 0
          git push
